# Generated by Django 4.1.5 on 2023-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.EmailField(max_length=255),
        ),
    ]
