# Generated by Django 4.1.5 on 2023-08-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
        ('users', '0007_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='langue',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='formation.langue'),
        ),
    ]
