# Generated by Django 4.1.5 on 2023-07-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampLexicale',
            fields=[
                ('id_ChampLexicale', models.AutoField(primary_key=True, serialize=False)),
                ('NomChamp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id_langue', models.AutoField(primary_key=True, serialize=False)),
                ('libelleLangue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MotFr',
            fields=[
                ('id_Mot', models.AutoField(primary_key=True, serialize=False)),
                ('ecriture', models.TextField(null=True)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NiveauFormation',
            fields=[
                ('id_Niveau', models.AutoField(primary_key=True, serialize=False)),
                ('libelleNiveauFormation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TempsVerbaux',
            fields=[
                ('id_TempsVerbaux', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleTempsVerbaux', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id_theme', models.AutoField(primary_key=True, serialize=False)),
                ('libelleThem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VerbeFr',
            fields=[
                ('id_Verbe', models.AutoField(primary_key=True, serialize=False)),
                ('libelleVerbe', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traduires',
            fields=[
                ('id_Traduire', models.AutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(null=True, upload_to='public/motTraduit')),
                ('motTraduit', models.CharField(default=1, max_length=100)),
                ('id_Mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Traduction', to='formation.motfr')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradLang', to='formation.langue')),
            ],
        ),
        migrations.CreateModel(
            name='Regles',
            fields=[
                ('id_Regles', models.AutoField(primary_key=True, serialize=False)),
                ('libelleRegles', models.TextField()),
                ('id_TempsVerbaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.tempsverbaux')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.langue')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id_Dialogue', models.AutoField(primary_key=True, serialize=False)),
                ('libelleDialogue', models.TextField(null=True)),
                ('audio', models.FileField(null=True, upload_to='public/Dialogue')),
                ('regles', models.TextField(null=True)),
                ('id_Langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.langue')),
                ('id_Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.niveauformation')),
                ('id_Themes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id_Contenir', models.AutoField(primary_key=True, serialize=False)),
                ('corpus', models.TextField(default='')),
                ('tradCorpus', models.TextField(default='')),
                ('NomChamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champ', to='formation.champlexicale')),
                ('id_Mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mots', to='formation.motfr')),
            ],
        ),
        migrations.CreateModel(
            name='Conjuguer',
            fields=[
                ('id_Conjuguer', models.AutoField(primary_key=True, serialize=False)),
                ('libelleConjuguer', models.TextField()),
                ('id_TempsVerbaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.tempsverbaux')),
                ('id_Verbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.verbefr')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.langue')),
            ],
        ),
        migrations.AddField(
            model_name='champlexicale',
            name='Nivform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='formation.niveauformation'),
        ),
    ]
