# Generated by Django 4.1.6 on 2023-02-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('idChant', models.AutoField(primary_key=True, serialize=False)),
                ('nomChant', models.CharField(max_length=100)),
                ('descriptionChant', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Conte',
            fields=[
                ('idConte', models.AutoField(primary_key=True, serialize=False)),
                ('nomConte', models.CharField(max_length=100)),
                ('descriptionConte', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('idLangue', models.AutoField(primary_key=True, serialize=False)),
                ('nomLangue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proverbe',
            fields=[
                ('idProverbe', models.AutoField(primary_key=True, serialize=False)),
                ('nomProverbe', models.CharField(max_length=100)),
                ('descriptionProverbe', models.TextField()),
                ('idLangue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.langue')),
            ],
        ),
        migrations.DeleteModel(
            name='apprenant',
        ),
        migrations.AddField(
            model_name='conte',
            name='idLangue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.langue'),
        ),
        migrations.AddField(
            model_name='chant',
            name='idLangue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.langue'),
        ),
    ]
