# Generated by Django 4.1.6 on 2023-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_chant_conte_langue_proverbe_delete_apprenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chant',
            name='traductionFrancais',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='conte',
            name='traductionFrancais',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='proverbe',
            name='traductionFrancais',
            field=models.TextField(default=1),
        ),
    ]
