# Generated by Django 4.1.2 on 2023-02-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_chant_traductionfrancais_conte_traductionfrancais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chant',
            name='descriptionChant',
        ),
        migrations.AlterField(
            model_name='conte',
            name='idLangue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langue', to='culture.langue'),
        ),
    ]
