# Generated by Django 4.1.2 on 2023-02-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_remove_chant_descriptionchant_alter_conte_idlangue'),
    ]

    operations = [
        migrations.AddField(
            model_name='proverbe',
            name='theme',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='chant',
            name='idLangue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantlangue', to='culture.langue'),
        ),
        migrations.AlterField(
            model_name='chant',
            name='nomChant',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='conte',
            name='idLangue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contelangue', to='culture.langue'),
        ),
        migrations.AlterField(
            model_name='conte',
            name='nomConte',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='langue',
            name='nomLangue',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proverbe',
            name='idLangue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proverbelangue', to='culture.langue'),
        ),
        migrations.AlterField(
            model_name='proverbe',
            name='nomProverbe',
            field=models.CharField(max_length=200),
        ),
    ]
