# Generated by Django 4.1.2 on 2023-02-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0005_proverbe_theme_alter_chant_idlangue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chant',
            name='parole',
            field=models.TextField(default=1),
        ),
    ]
