# Generated by Django 4.1.2 on 2023-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0006_chant_parole'),
    ]

    operations = [
        migrations.AddField(
            model_name='chant',
            name='audio',
            field=models.FileField(blank=True, upload_to='public/audiochant'),
        ),
    ]
