# Generated by Django 4.1.2 on 2023-02-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0007_chant_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chant',
            old_name='audio',
            new_name='audioChant',
        ),
        migrations.AddField(
            model_name='conte',
            name='audioConte',
            field=models.FileField(blank=True, upload_to='public/audioconte'),
        ),
        migrations.AddField(
            model_name='proverbe',
            name='audioProverbe',
            field=models.FileField(blank=True, upload_to='public/audioProverbe'),
        ),
    ]
