# Generated by Django 4.1.2 on 2023-02-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0008_rename_audio_chant_audiochant_conte_audioconte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proverbe',
            name='nomProverbe',
        ),
    ]
